// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmapUnWCOxpcr_eAsRBhWVFZBm_jQdhTo',
    appId: '1:923569375017:web:910c07375db7771a749938',
    messagingSenderId: '923569375017',
    projectId: 'eateaseappwebdb',
    authDomain: 'eateaseappwebdb.firebaseapp.com',
    storageBucket: 'eateaseappwebdb.firebasestorage.app',
    measurementId: 'G-MRQ3S6GJK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMjgF2tvxdnDFZH94EnWLpJvThtl4Oxnw',
    appId: '1:923569375017:android:b9f4625207cf5636749938',
    messagingSenderId: '923569375017',
    projectId: 'eateaseappwebdb',
    storageBucket: 'eateaseappwebdb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmapUnWCOxpcr_eAsRBhWVFZBm_jQdhTo',
    appId: '1:923569375017:web:f3d7b9232c53c479749938',
    messagingSenderId: '923569375017',
    projectId: 'eateaseappwebdb',
    authDomain: 'eateaseappwebdb.firebaseapp.com',
    storageBucket: 'eateaseappwebdb.firebasestorage.app',
    measurementId: 'G-PXNFS29XVD',
  );
}
